# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('lugardelhecho', models.CharField(max_length=50)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.DateTimeField(verbose_name='Hora')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('personalid', models.IntegerField(default=2)),
            ],
        ),
    ]
